products:
  - title: Samsonite Tectonic Crossbody Bag
    image: https://m.media-amazon.com/images/I/81I6bSy6DdL._AC_SX679_.jpg
    link: https://www.amazon.com/dp/B0BGWQGVBK?tag=soukeynatraor-20
    description: Compact, durable travel bag perfect for daily adventures.
  - title: Portable Luggage Scale
    image: https://m.media-amazon.com/images/I/81wjLXQX6gL._SX522_.jpg
    link: https://www.amazon.com/dp/B00NW62PCA?tag=soukeynatraor-20
    description: Avoid overweight baggage fees with this digital luggage scale.
  - title: Coolife Suitcase Set 3 Piece Luggage Set Carry
    image: https://m.media-amazon.com/images/I/71ZZgBhFSqL._AC_SX679_.jpg
    link: https://amzn.to/3VvrAYi
    description: Five piece set offers a 20’’ luggage, a 24’’ luggage, a 28’’
  - title: 3 in 1 Travel Blanket Pillow Set
    image: https://m.media-amazon.com/images/I/71oiyLYWwyL._AC_SX679_.jpg
    link: https://amzn.to/46MPPaC
    description: The blanket is made of ultra-soft flannel fabric, 100% polyester
      and 350gsm thickness.
  - title: SHOWKOO Luggage Sets Expandable PC+ABS Durable Suitcase Double Wheels TSA
      Lock Lavender Purple 3pcs
    image: https://m.media-amazon.com/images/I/81-92BXCUfL._AC_SX679_.jpg
    link: https://amzn.to/4nLB0La
    description: "Top Quality Luggage Sets: Made of brand new extra-thick PC+ABS
      materials for hardshell, which make the luggage more durable, lighter and
      impact-resistant. Features textured finish to prevent against scratches,
      keeping cases beautiful after a trip. 20in is best for carryon (not
      expandable), 24in & 28in expands 20% for more Spaces. Capacity : 20in33L
      24in63L 28in 93L."
