- title: "Samsonite Tectonic Crossbody Bag"
  image: "https://m.media-amazon.com/images/I/81I6bSy6DdL._AC_SX679_.jpg"
  link: "https://www.amazon.com/dp/B0BGWQGVBK?tag=soukeynatraor-20"
  description: "Compact, durable travel bag perfect for daily adventures."

- title: "Portable Luggage Scale"
  image: "https://m.media-amazon.com/images/I/71O-vl9Xr5L._AC_SL1500_.jpg"
  link: "https://www.amazon.com/dp/B00NW62PCA?tag=soukeynatraor-20"
  description: "Avoid overweight baggage fees with this digital luggage scale."

- title: "Travel Neck Pillow"
  image: "https://m.media-amazon.com/images/I/81jvXvU8SIL._AC_SL1500_.jpg"
  link: "https://www.amazon.com/dp/B01JPJQWQO?tag=soukeynatraor-20"
  description: "Memory foam pillow for long flights and comfort."

- title: "Universal Travel Adapter"
  image: "https://m.media-amazon.com/images/I/71FWyZ6WZkL._AC_SL1500_.jpg"
  link: "https://www.amazon.com/dp/B01N6S068R?tag=soukeynatraor-20"
  description: "Stay charged anywhere with this universal adapter."
