name: Generate Categories & Tags

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run generator
        run: bash _scripts/generate_taxonomies.sh

      - name: Commit & push generated files
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add _categories _tags || true
          git commit -m "Auto-generate categories and tags" || echo "No changes"
          git push
