name: Auto Generate Categories & Tags

on:
  push:
    branches: [ main ]
    paths:
      - '_posts/**'

permissions:
  contents: write   # ✅ allows the workflow to push changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ✅ fetch full history so push works

      - name: Run taxonomy generator
        run: bash _scripts/generate_taxonomies.sh

      - name: Commit & push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _categories _tags || true
          git commit -m "Auto-generate categories and tags" || echo "No changes to commit"
          git pull --rebase origin main || true  # ✅ pulls latest before pushing
          git push origin main || echo "Nothing to push"
